package me.WiebeHero.EnchantmentAPI;

public class EnchantmentCondition {
	public enum Condition{
		FALL,
		FIRE,
		DROWNING,
		ENTITY_DAMAGE_BY_ENTITY,
		ENTITY_EXPLOSION,
		BLOCK_EXPLOSION,
		DRAGON_BREATH,
		ENTITY_DEATH,
		ENTITY_DEATH_MELEE,
		ENTITY_DEATH_PROJECTILE,
		PLAYER_DEATH,
		PLAYER_DEATH_MELEE,
		PLAYER_DEATH_PROJECTILE,
		BLOCKING,
		RIGHT_CLICK,
		LEFT_CLICK,
		ENTITY_SWEEP_ATTACK,
		PROJECTILE_DAMAGE,
		PROJECTILE_SHOOT,
		PROJECTILE_LAND,
		LAVA,
		HOT_FLOOR,
		LIGHTNING,
		MAGIC,
		POISON,
		WITHER,
		ARMOR_CHANGE,
		CONSUME,
		FOOD_CHANGE_UP,
		FOOD_CHANGE_DOWN,
		KILLED_ENTITY
	}
}
