package Skills;

import java.util.ArrayList;

import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.Listener;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.SkullMeta;

import me.WiebeHero.CustomEnchantments.ColorCodeTranslator;
import me.WiebeHero.CustomEnchantments.CustomEnchantments;

public class ClassMenu implements Listener{
	public void ClassSelect (Player player) {
		Inventory i = CustomEnchantments.getInstance().getServer().createInventory(null, 54, (new ColorCodeTranslator().colorize("&6Class Selection: &b" + player.getName())));
		i.setItem(0, empty());
		i.setItem(1, empty());
		i.setItem(2, empty());
		i.setItem(3, empty());
		i.setItem(4, infoBook());
		i.setItem(5, infoSkills());
		i.setItem(6, empty());
		i.setItem(7, empty());
		i.setItem(8, empty());
		i.setItem(9, empty());
		i.setItem(10, empty());
		i.setItem(11, empty());
		i.setItem(12, empty());
		i.setItem(13, empty());
		i.setItem(14, empty());
		i.setItem(15, empty());
		i.setItem(16, empty());
		i.setItem(17, empty());
		i.setItem(18, empty());
		i.setItem(19, classWrath(0));
		i.setItem(20, empty());
		i.setItem(21, classLust(0));
		i.setItem(22, empty());
		i.setItem(23, classGluttony(0));
		i.setItem(24, empty());
		i.setItem(25, classGreed(0));
		i.setItem(26, empty());
		i.setItem(27, empty());
		i.setItem(28, empty());
		i.setItem(29, empty());
		i.setItem(30, empty());
		i.setItem(31, empty());
		i.setItem(32, empty());
		i.setItem(33, empty());
		i.setItem(34, empty());
		i.setItem(35, empty());
		i.setItem(36, empty());
		i.setItem(37, empty());
		i.setItem(38, classSloth(0));
		i.setItem(39, empty());
		i.setItem(40, classEnvy(0));
		i.setItem(41, empty());
		i.setItem(42, classPride(0));
		i.setItem(43, empty());
		i.setItem(44, empty());
		i.setItem(45, empty());
		i.setItem(46, empty());
		i.setItem(47, empty());
		i.setItem(48, empty());
		i.setItem(49, empty());
		i.setItem(50, empty());
		i.setItem(51, empty());
		i.setItem(52, empty());
		i.setItem(53, empty());
		player.openInventory(i);
	}
	public void ClassConfirm (Player player, String classTitle, ItemStack classHead) {
		Inventory i = CustomEnchantments.getInstance().getServer().createInventory(null, 9, (new ColorCodeTranslator().colorize("&6Class: " + classTitle)));
		i.setItem(0, empty());
		i.setItem(1, empty());
		i.setItem(2, yesButton());
		i.setItem(3, empty());
		i.setItem(4, classHead);
		i.setItem(5, empty());
		i.setItem(6, noButton());
		i.setItem(7, empty());
		i.setItem(8, empty());
		player.openInventory(i);
	}
	public ItemStack empty() {
		ItemStack i = new ItemStack(Material.GRAY_STAINED_GLASS_PANE, 1);
		ItemMeta m = i.getItemMeta();
		m.setDisplayName(new ColorCodeTranslator().colorize(" "));
		i.setItemMeta(m);
		return i;
	}
	public ItemStack yesButton() {
		ItemStack i = new ItemStack(Material.LIME_STAINED_GLASS_PANE, 1);
		ItemMeta m = i.getItemMeta();
		m.setDisplayName(new ColorCodeTranslator().colorize("&aYes"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&aAccept this class."));
		lore.add(new ColorCodeTranslator().colorize("&4Warning!"));
		lore.add(new ColorCodeTranslator().colorize("&cIf you choose yes, you won't be"));
		lore.add(new ColorCodeTranslator().colorize("&cable to change your class for a while!"));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
	public ItemStack noButton() {
		ItemStack i = new ItemStack(Material.RED_STAINED_GLASS_PANE, 1);
		ItemMeta m = i.getItemMeta();
		m.setDisplayName(new ColorCodeTranslator().colorize("&cNo"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&cDeny this class and go back to the selection menu."));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
	public ItemStack infoBook() {
		ItemStack i = new ItemStack(Material.ENCHANTED_BOOK, 1);
		ItemMeta m = i.getItemMeta();
		m.setDisplayName(new ColorCodeTranslator().colorize("&6&lInfo Classes"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7What are Classes?:"));
		lore.add(new ColorCodeTranslator().colorize("&7Classes are sins you chose, each class"));
		lore.add(new ColorCodeTranslator().colorize("&7Has 2 upsides (+) and 2 downsides (-)"));
		lore.add(new ColorCodeTranslator().colorize("&7Upsides increase the base skill upgrade by 50%."));
		lore.add(new ColorCodeTranslator().colorize("&7Downsides decrease the base skill upgrade by 50%."));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7What are Abilities?:"));
		lore.add(new ColorCodeTranslator().colorize("&7Each class has their own ability that helps"));
		lore.add(new ColorCodeTranslator().colorize("&7them in combat. These abilities become better based"));
		lore.add(new ColorCodeTranslator().colorize("&7on your current Player Level. Or you can unlock Ability Modifiers"));
		lore.add(new ColorCodeTranslator().colorize("&7that give bonusses to your ability."));
		lore.add(new ColorCodeTranslator().colorize("&c&lIMPORTANT: &7Downsides dont have Ability Modifiers."));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7What are skills?:"));
		lore.add(new ColorCodeTranslator().colorize("&7When you do /skills a menu will pop up. These skills range"));
		lore.add(new ColorCodeTranslator().colorize("&7from Attack Damage to Defense. Hover over the feather to"));
		lore.add(new ColorCodeTranslator().colorize("&7see what the skills do. You gain skill points from leveling up"));
		lore.add(new ColorCodeTranslator().colorize("&7which you can put in skills that help you in PVP/PVE."));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
	public ItemStack infoSkills() {
		ItemStack i = new ItemStack(Material.FEATHER, 1);
		ItemMeta m = i.getItemMeta();
		m.setDisplayName(new ColorCodeTranslator().colorize("&6&lInfo Skills"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&5Attack Damage:"));
		lore.add(new ColorCodeTranslator().colorize("&7Increase the damage you deal through melee."));
		lore.add(new ColorCodeTranslator().colorize("&7Base: &62.5%+"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&9Attack Speed"));
		lore.add(new ColorCodeTranslator().colorize("&7You can attack faster."));
		lore.add(new ColorCodeTranslator().colorize("&7Base: &60.4%+"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7Critical Chance:"));
		lore.add(new ColorCodeTranslator().colorize("&7Have a chance to deal double damage. (Melee/Ranged)"));
		lore.add(new ColorCodeTranslator().colorize("&7Base: &60.5%+"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&dRanged Damage:"));
		lore.add(new ColorCodeTranslator().colorize("&7Increase the damage you deal through ranged attacks."));
		lore.add(new ColorCodeTranslator().colorize("&7Base: &63%+"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&cHealth:"));
		lore.add(new ColorCodeTranslator().colorize("&7Increase your MAX HP."));
		lore.add(new ColorCodeTranslator().colorize("&7Base: &65%+"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&8Defense"));
		lore.add(new ColorCodeTranslator().colorize("&7Increase the amount of armor points you recieve from armor."));
		lore.add(new ColorCodeTranslator().colorize("&7Base: &63.33%+"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7If a skill is your upside, their base upgrade value is increased by 50%"));
		lore.add(new ColorCodeTranslator().colorize("&7If a skill is your downside, their base upgrade value is decreased by 50%"));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
	public ItemStack classWrath(int level) {
		ItemStack i = CustomEnchantments.getInstance().createHead("http://textures.minecraft.net/texture/c2fe7fd16c064dda14405ee4b710b3852533ec6a9b9b1aa8c02374273ea789b");
		SkullMeta m = (SkullMeta) i.getItemMeta();
		int finalLevel = level;
		double damage1 = 5 + finalLevel * 0.15;
		double damage2 = 0.1 + finalLevel * 0.01;
		double range = 4 + finalLevel * 0.06;
		double cooldown = 130 - finalLevel * 0.25;
		m.setDisplayName(new ColorCodeTranslator().colorize("&4&lWrath"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&4Attack Damage +"));
		lore.add(new ColorCodeTranslator().colorize("&5Critical Chance +"));
		lore.add(new ColorCodeTranslator().colorize("&cHealth -"));
		lore.add(new ColorCodeTranslator().colorize("&8Defense -"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7Ability: &6Hatred of the Wrath."));
		lore.add(new ColorCodeTranslator().colorize("&7This Ability, when activated deals &4" + String.format("%.2f", damage1) +" Damage"));
		lore.add(new ColorCodeTranslator().colorize("&7to your sorounding enemies. Additionally,"));
		lore.add(new ColorCodeTranslator().colorize("&7every time an enemy hits you, the damage they"));
		lore.add(new ColorCodeTranslator().colorize("&7will recieve will be increased by &4" + String.format("%.2f", damage2) +" Damage."));
		lore.add(new ColorCodeTranslator().colorize("&7This extra damage period will run out after &b5 Seconds"));
		lore.add(new ColorCodeTranslator().colorize("&7If you are not hit by the attacker again."));
		lore.add(new ColorCodeTranslator().colorize("&7The range of this attack is &6" + String.format("%.2f", range) + " Blocks"));
		lore.add(new ColorCodeTranslator().colorize("&7Cooldown: &b" + cooldown + " Seconds"));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
	public ItemStack classLust(int level) {
		ItemStack i = CustomEnchantments.getInstance().createHead("http://textures.minecraft.net/texture/78aea514edd846a3ff89024ba853cba873907dab62930d7f7c7ec83f66719086");
		SkullMeta m = (SkullMeta) i.getItemMeta();
		int finalLevel = level;
		double heal = 10 + finalLevel * 0.15;
		double damage = 1 + finalLevel * 0.04;
		double range = 7 + finalLevel * 0.07;
		double cooldown = 100 - finalLevel * 0.3;
		m.setDisplayName(new ColorCodeTranslator().colorize("&d&lLust"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&cHealth +"));
		lore.add(new ColorCodeTranslator().colorize("&dRanged Damage +"));
		lore.add(new ColorCodeTranslator().colorize("&4Attack Damage -"));
		lore.add(new ColorCodeTranslator().colorize("&9Attack Speed -"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7Ability: &6Drain Blood"));
		lore.add(new ColorCodeTranslator().colorize("&7This Ability, when activated this heals you for &c" + String.format("%.2f", heal) + "% of your MAX HP"));
		lore.add(new ColorCodeTranslator().colorize("&7additionally, you drain the life of nearby enemies."));
		lore.add(new ColorCodeTranslator().colorize("&7Damaging them by &4" + String.format("%.2f", damage) + "% of their MAX HP."));
		lore.add(new ColorCodeTranslator().colorize("&7You will also heal the health you dealt as damage."));
		lore.add(new ColorCodeTranslator().colorize("&7in a &6" + String.format("%.2f", range) + " &7block radius."));
		lore.add(new ColorCodeTranslator().colorize("&7Cooldown: &b" + String.format("%.2f", cooldown) + " Seconds"));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
	public ItemStack classGluttony(int level) {
		ItemStack i = CustomEnchantments.getInstance().createHead("http://textures.minecraft.net/texture/61678bc9a728804ff41a88d56ed63ab3248a77a821a11718639b391ad522549e");
		SkullMeta m = (SkullMeta) i.getItemMeta();
		int finalLevel = level;
		double heal = 10 + finalLevel * 0.25;
		double decrease = 20 + finalLevel * 0.30;
		double duration = 10 + finalLevel * 0.10;
		double cooldown = 115 - finalLevel * 0.2;
		m.setDisplayName(new ColorCodeTranslator().colorize("&c&lGluttony"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&cHealth +"));
		lore.add(new ColorCodeTranslator().colorize("&8Defense +"));
		lore.add(new ColorCodeTranslator().colorize("&4Attack Damage -"));
		lore.add(new ColorCodeTranslator().colorize("&dRanged Damage -"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7Ability: &6Stand"));
		lore.add(new ColorCodeTranslator().colorize("&7You stand in a defensefull position, you &8decrease incoming damage"));
		lore.add(new ColorCodeTranslator().colorize("&8by " + String.format("%.2f", decrease) + "% for &b" + String.format("%.2f", duration) + " seconds. &7Additionally, you &cheal " + String.format("%.2f", heal) +"% of your MAX HP"));
		lore.add(new ColorCodeTranslator().colorize("&7Cooldown: &b" + String.format("%.2f", cooldown) + " Seconds"));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
	public ItemStack classGreed(int level) {
		ItemStack i = CustomEnchantments.getInstance().createHead("http://textures.minecraft.net/texture/ec4d37a83af45d30e4b6e4793f9966d0034ab08f825e1e71a91cc2acb8c92178");
		SkullMeta m = (SkullMeta) i.getItemMeta();
		int finalLevel = level;
		double damage = 50 + finalLevel * 0.50;
		double attackS = 20 + finalLevel * 0.30;
		double duration = 6.5 + finalLevel * 0.05;
		double cooldown = 100 - finalLevel * 0.3;
		m.setDisplayName(new ColorCodeTranslator().colorize("&9&lGreed"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&dRanged Damage +"));
		lore.add(new ColorCodeTranslator().colorize("&9Attack Speed +"));
		lore.add(new ColorCodeTranslator().colorize("&cHealth -"));
		lore.add(new ColorCodeTranslator().colorize("&8Defense -"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7Ability: &6Hunting Arrow"));
		lore.add(new ColorCodeTranslator().colorize("&7When you activate your ability, the next ranged attack that hits your enemy"));
		lore.add(new ColorCodeTranslator().colorize("&7causes them to take &4" + String.format("%.2f", damage) + "% extra damage from any source &7for &b" + String.format("%.2f", duration) + " Seconds"));
		lore.add(new ColorCodeTranslator().colorize("&7Additionally, your &9attack speed is increased by " + String.format("%.2f", attackS) + "%"));
		lore.add(new ColorCodeTranslator().colorize("&7Cooldown: &b" + String.format("%.2f", cooldown) + " Seconds"));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
	public ItemStack classSloth(int level) {
		ItemStack i = CustomEnchantments.getInstance().createHead("http://textures.minecraft.net/texture/ca35eb10b94e888427fb23c783082658ceb81f3cf5d0aad25d7d41a194b26");
		SkullMeta m = (SkullMeta) i.getItemMeta();
		int finalLevel = level;
		double arrow = 10 + finalLevel * 0.25;
		double damage = 4 + finalLevel * 0.11;
		double duration = 2 + finalLevel * 0.08;
		double cooldown = 65 - finalLevel * 0.15;
		m.setDisplayName(new ColorCodeTranslator().colorize("&5&lSloth"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&5Critical Chance +"));
		lore.add(new ColorCodeTranslator().colorize("&8Defense +"));
		lore.add(new ColorCodeTranslator().colorize("&dRanged Damage -"));
		lore.add(new ColorCodeTranslator().colorize("&9Attack Speed -"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7Ability: &6Deadly Thorns"));
		lore.add(new ColorCodeTranslator().colorize("&7When you activate your ability, you will fire " + String.format("%.0f", arrow) + " arrows from your back."));
		lore.add(new ColorCodeTranslator().colorize("&7These arrows will deal &4" + String.format("%.2f", damage) + " Damage &7and will apply "));
		lore.add(new ColorCodeTranslator().colorize("&apoison 2 &7for &b" + String.format("%.2f", duration) + " seconds &7on the enemy that it hits."));
		lore.add(new ColorCodeTranslator().colorize("&7Cooldown: &b" + String.format("%.2f", cooldown) + " Seconds"));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
	public ItemStack classEnvy(int level) {
		ItemStack i = CustomEnchantments.getInstance().createHead("http://textures.minecraft.net/texture/ad6edc436ffc19a185855a060f974382ec9225b6f4db26895818bb7adca2ea5b");
		SkullMeta m = (SkullMeta) i.getItemMeta();
		int finalLevel = level;
		double damage = 50 + finalLevel * 0.50;
		double heal = 10 + finalLevel * 0.4;
		double duration = 5 + finalLevel * 0.05;
		double cooldown = 90 - finalLevel * 0.25;
		m.setDisplayName(new ColorCodeTranslator().colorize("&8&lEnvy"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&4Attack Damage +"));
		lore.add(new ColorCodeTranslator().colorize("&dRanged Damage +"));
		lore.add(new ColorCodeTranslator().colorize("&5Critical Chance -"));
		lore.add(new ColorCodeTranslator().colorize("&9Attack Speed -"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7Ability: &6Special Attack"));
		lore.add(new ColorCodeTranslator().colorize("&7When you activate your ability, your next attack will deal &4" + String.format("%.2f", damage) + "% Extra Damage."));
		lore.add(new ColorCodeTranslator().colorize("&7Additionally, you recover &c" + String.format("%.2f", heal) + "% of the damage done as HP."));
		lore.add(new ColorCodeTranslator().colorize("&7You have &b" + String.format("%.2f", duration) + " seconds &7to execute the attack."));
		lore.add(new ColorCodeTranslator().colorize("&7Cooldown: &b" + String.format("%.2f", cooldown) + " Seconds"));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
	public ItemStack classPride(int level) {
		ItemStack i = CustomEnchantments.getInstance().createHead("http://textures.minecraft.net/texture/4f950f8087f0396362cc817e6d024f35bd3aa09f2e44c601bab326ac8ba805f9");
		SkullMeta m = (SkullMeta) i.getItemMeta();
		int finalLevel = level;
		double speed = 20 + finalLevel * 0.30;
		double decrease = 10 + finalLevel * 0.15;
		double duration = 7 + finalLevel * 0.10;
		double cooldown = 100 - finalLevel * 0.30;
		m.setDisplayName(new ColorCodeTranslator().colorize("&6&lPride"));
		ArrayList<String> lore = new ArrayList<String>();
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&9Attack Speed +"));
		lore.add(new ColorCodeTranslator().colorize("&8Defense +"));
		lore.add(new ColorCodeTranslator().colorize("&5Critical Chance -"));
		lore.add(new ColorCodeTranslator().colorize("&cHealth -"));
		lore.add(new ColorCodeTranslator().colorize("&7-------------------"));
		lore.add(new ColorCodeTranslator().colorize("&7Ability: &6Quick Attack"));
		lore.add(new ColorCodeTranslator().colorize("&7When you activate your ability, your &9movement speed increases by " + String.format("%.2f", speed) + "%"));
		lore.add(new ColorCodeTranslator().colorize("&7Additionally, you reduce &8" + String.format("%.2f", decrease) + "% of any incomming damage"));
		lore.add(new ColorCodeTranslator().colorize("&7and increase your &9attack speed by " + String.format("%.2f", decrease) + "while this is active."));
		lore.add(new ColorCodeTranslator().colorize("&7This effect runs out after &b" + String.format("%.2f", duration) + " seconds."));
		lore.add(new ColorCodeTranslator().colorize("&7Cooldown: &b" + String.format("%.2f", cooldown) + " Seconds"));
		m.setLore(lore);
		i.setItemMeta(m);
		return i;
	}
}
