package Skills;

public class SkillEnum {
	public enum Skills{
		LEVEL,
		XP,
		MAXXP,
		SKILL_POINTS,
		ATTACK_DAMAGE,
		ATTACK_SPEED,
		CRITICAL_CHANCE,
		RANGED_DAMAGE,
		MAX_HEALTH,
		ARMOR_DEFENSE,
		ATTACK_DAMAGE_MODIFIER,
		ATTACK_SPEED_MODIFIER,
		CRITICAL_CHANCE_MODIFIER,
		RANGED_DAMAGE_MODIFIER,
		MAX_HEALTH_MODIFIER,
		ARMOR_DEFENSE_MODIFIER,
		ATTACK_DAMAGE_CALC,
		ATTACK_SPEED_CALC,
		CRITICAL_CHANCE_CALC,
		RANGED_DAMAGE_CALC,
		MAX_HEALTH_CALC,
		ARMOR_DEFENSE_CALC,
		ATTACK_DAMAGE_EXTRA,
		ATTACK_SPEED_EXTRA,
		CRITICAL_CHANCE_EXTRA,
		RANGED_DAMAGE_EXTRA,
		MAX_HEALTH_EXTRA,
		ARMOR_DEFENSE_EXTRA
	}
}
