name: CustomEnchantments
author: WiebeHero
version: 0.352
api-version: 1.13
softdepend: [Multiverse-Core, WorldEdit, WorldGuard]
main: me.WiebeHero.CustomEnchantments.CustomEnchantments
description: Custom Enchantment coded in java for DungeonForge

commands:
  skill:
    ussage: /<command>
    description: 'Command for opening skills'
    aliases: [skills]
  faction:
    ussage: /<command>
    description: 'Command for Factions'
    aliases: [f]
  rtp:
    ussage: /<command>
    description: 'Command for rtp'
  spawn:
    ussage: /<command>
    description: 'Command for spawn'
  pay:
    ussage: /<command>
    description: 'Command for paying players'
  balance:
    ussage: /<command>
    description: 'Command for checking your balance'
    aliases: [bal]
  money:
    ussage: /<command>
    description: 'Command for checking your balance'
  sethome:
    ussage: /<command>
    description: 'Command for sethome'
  home:
    ussage: /<command>
    description: 'Command for home'
  delhome:
    ussage: /<command>
    description: 'Command for delhome'
  homes:
    ussage: /<command>
    description: 'Command for homes'
  tpa:
    ussage: /<command>
    description: 'Command for tpa'
  tpaccept:
    ussage: /<command>
    description: 'Command for tpahere'
  tpahere:
    ussage: /<command>
    description: 'Command for tpaccept'
  tpdeny:
    ussage: /<command>
    description: 'Command for tpadeny'
  tpatoggle:
    ussage: /<command>
    description: 'Command for tpatoggle'
  staffmode:
    ussage: /<command>
    description: 'Command for staffmode'
  ban:
    ussage: /<command>
    description: 'Command for ban'
  unban:
    ussage: /<command>
    description: 'Command for unban'
  mute:
    ussage: /<command>
    description: 'Command for mute'
  unmute:
    ussage: /<command>
    description: 'Command for unmute'
  warn:
    ussage: /<command>
    description: 'Command for warn'
  msg:
    ussage: /<command>
    description: 'Command for msg'
  ignore:
    ussage: /<command>
    description: 'Command for ignore'
  checkstaff:
    ussage: /<command>
    description: 'Command for checkstaff'
  rank:
    ussage: /<command>
    description: 'Command for rank'
  procedure:
    ussage: /<command>
    description: 'Command for initiating procedure'
  ah:
    ussage: /<command>
    description: 'Command for initiating ah'
    aliases: [auctionhouse]
  unwarn:
    ussage: /<command>
    description: 'Command for unwarn'
  party:
    ussage: /<command>
    aliases: [p]
    description: 'Command for party'
  kit:
    ussage: /<command>
    description: 'Command for kit'
  kits:
    ussage: /<command>
    description: 'Command for kit'
  punish:
    ussage: /<command>
    description: 'Command for giving custom items'
  history:
    ussage: /<command>
    description: 'Command for setting levels'
  stafflist:
    ussage: /<command>
    description: 'Command for setting levels'
  staffchat:
    ussage: /<command>
    description: 'Command for setting levels'
    aliases: [sc]
  checkmute:
    ussage: /<command>
    description: 'Command for setting levels'
  checkban:
    ussage: /<command>
    description: 'Command for setting levels'
  clearchat:
    ussage: /<command>
    description: 'Command for setting levels'
  freeze:
    ussage: /<command>
    description: 'Command for setting levels'
  unfreeze:
    ussage: /<command>
    description: 'Command for setting levels'
  fly:
    ussage: /<command>
    description: 'Command for setting levels'
  feed:
    ussage: /<command>
    description: 'Command for setting levels'
  heal:
    ussage: /<command>
    description: 'Command for setting levels'
  time:
    ussage: /<command>
    description: 'Command for setting levels'
  weather:
    ussage: /<command>
    description: 'Command for setting levels'
  checkmode:
    ussage: /<command>
    description: 'Command for setting levels'
  clearinventory:
    ussage: /<command>
    description: 'Command for setting levels'
  tp:
    ussage: /<command>
    description: 'Command for setting levels'
  tptp:
    ussage: /<command>
    description: 'Command for setting levels'
  tphere:
    ussage: /<command>
    description: 'Command for setting levels'
  af:
    ussage: /<command>
    description: 'Command for setting levels'
  a:
    ussage: /<command>
    description: 'Command for admins'
  god:
    ussage: /<command>
    description: 'Command for setting levels'
  gamemode:
    ussage: /<command>
    description: 'Command for setting levels'
    aliases: [gm]
  item:
    ussage: /<command>
    description: 'Command for setting levels'
  capturepoints:
    ussage: /<command>
    description: 'Command for setting levels'
    aliases: [cp]
  trade:
    ussage: /<command>
    description: 'Command for setting levels'